name: Slack Notifications with statuses
author: Asugawara
description: GithubAction2Slack is Action to post GithubActions Workflow status into Slack channel via webhook URL on Python3.
inputs:
  GITHUB_TOKEN:
    required: true
  SLACK_WEBHOOK_URL:
    required: true
  MENTION_MAP:
    required: false
  STATUS_EMOJI_MAP:
    required: false
  NAME:
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
